/**
 * Interactive / non-interactive `uddns init` wizard.
 */

import { access, writeFile } from 'node:fs/promises';
import * as readline from 'node:readline/promises';

import { DEFAULT_INTERVAL_MS, DEFAULT_PROVIDER, PROVIDER_IDS_LIST } from './init-defaults.js';
import { MIN_INTERVAL_MS } from './defaults.js';
import { createLogger, formatError, type Logger } from './log.js';

export type InitOptions = {
  defaults?: boolean;
  force?: boolean;
  cwd?: string;
  envPath?: string;
  log?: Logger;
  stdin?: NodeJS.ReadableStream;
  stdout?: NodeJS.WritableStream;
  ask?: (question: string) => Promise<string>;
  exit?: (code: number) => void;
  argv?: string[];
};

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

export function buildEnvContents(values: {
  provider: string;
  hosts: string;
  interval: string;
}): string {
  return [
    `# Generated by uddns init`,
    `UDDNS_PROVIDER=${values.provider}`,
    `UDDNS_HOSTS=${values.hosts}`,
    `UDDNS_INTERVAL=${values.interval}`,
    `UDDNS_LOG_LEVEL=info`,
    '',
    '# Fill in provider credentials — see docs/providers.md and .env.example',
    '',
  ].join('\n');
}

export async function runInit(options: InitOptions = {}): Promise<void> {
  const log = options.log ?? createLogger();
  const cwd = options.cwd ?? process.cwd();
  const envPath = options.envPath ?? `${cwd}/.env`;
  const exit = options.exit ?? ((code: number) => process.exit(code));

  try {
    if ((await fileExists(envPath)) && !options.force) {
      throw new Error(`${envPath} already exists (pass --force to overwrite)`);
    }

    let provider: string = DEFAULT_PROVIDER;
    let hosts = 'home.example.com';
    let interval = String(DEFAULT_INTERVAL_MS);

    if (!options.defaults) {
      let ask = options.ask;
      let rl: readline.Interface | null = null;
      if (!ask) {
        rl = readline.createInterface({
          input: options.stdin ?? process.stdin,
          output: options.stdout ?? process.stdout,
        });
        ask = async (question: string) => rl!.question(question);
      }
      try {
        const providerAnswer = (
          await ask(`Provider [${PROVIDER_IDS_LIST.join('|')}] (${provider}): `)
        ).trim();
        if (providerAnswer) {
          provider = providerAnswer.toLowerCase();
        }
        if (!PROVIDER_IDS_LIST.includes(provider)) {
          throw new Error(`Unsupported provider "${provider}"`);
        }
        const hostsAnswer = (await ask(`Hosts (comma-separated) (${hosts}): `)).trim();
        if (hostsAnswer) {
          hosts = hostsAnswer;
        }
        const intervalAnswer = (await ask(`Interval ms (${interval}): `)).trim();
        if (intervalAnswer) {
          const parsed = Number(intervalAnswer);
          if (!Number.isFinite(parsed) || parsed < MIN_INTERVAL_MS) {
            throw new Error(`Interval must be a number of milliseconds >= ${MIN_INTERVAL_MS}`);
          }
          interval = intervalAnswer;
        }
      } finally {
        rl?.close();
      }
    }

    const contents = buildEnvContents({ provider, hosts, interval });
    await writeFile(envPath, contents, { encoding: 'utf8', mode: 0o600 });
    log.success(`Wrote ${envPath}`);
    log.info(
      'Next: fill provider credentials, then run `vp run config:check` or `uddns check-config`.',
    );
  } catch (error) {
    log.error('Init failed', formatError(error));
    exit(1);
  }
}
