name: Workflow lint

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

permissions: {}

concurrency:
  group: workflow-lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    permissions:
      contents: read
      security-events: write
    uses: bolens/.github/.github/workflows/reusable-actionlint.yml@d30ff6a56b47317d3d565e7b4747d133966db8d2
    with:
      security-audit: true
