name: Workflow lint

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

permissions: {}

concurrency:
  group: workflow-lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    permissions:
      contents: read
    uses: bolens/.github/.github/workflows/reusable-actionlint.yml@b179e4783aca035374a85da9676e0be893fa1701
    with:
      security-audit: true
